import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import "@stream-io/video-react-sdk/dist/css/styles.css";
import './globals.css'
import ConvexClerkProvider from '@/components/providers/ConvexClerkProvider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import NavBar from "../components/NavBar"
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexClerkProvider>
      

      <html lang="en" suppressHydrationWarning className='mx-[100px]'>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
             <NavBar />
            {children}
          </ThemeProvider>
          <Toaster />
        </body>
      </html>
      
    </ConvexClerkProvider>
  )
}